### ISSUE TITLE
video playback 8841658

### ISSUE THREAD

**Issue by dersphere** [dersphere/plugin.video.myvideo_de#2]
10:23:07 T:2876242752 NOTICE: -->Python Interpreter Initialized<--
10:23:07 T:2876242752 NOTICE: MyVideo.de addon: watch_video started with video_id: 8841658
10:23:07 T:2876242752 NOTICE: MyVideo.de scraper: get_video started with video_id: 8841658
10:23:07 T:2876242752 NOTICE: MyVideo.de scraper: __get_url opening url: http://www.myvideo.de/watch/8841658/
10:23:07 T:2876242752 NOTICE: MyVideo.de scraper: __get_url got 51023 bytes
10:23:07 T:2876242752 ERROR: Error Type: <type 'exceptions.AttributeError'>
10:23:07 T:2876242752 ERROR: Error Contents: 'NoneType' object has no attribute 'group'
10:23:07 T:2876242752 ERROR: Traceback (most recent call last):
File "/home/xbmc/.xbmc/addons/plugin.video.myvideo_de/addon.py", line 203, in <module>
plugin.run()
File "/home/xbmc/.xbmc/addons/script.module.xbmcswift/lib/xbmcswift/plugin.py", line 330, in run
self.dispatch(self.path)
File "/home/xbmc/.xbmc/addons/script.module.xbmcswift/lib/xbmcswift/plugin.py", line 129, in dispatch
return view_func(**items)
File "/home/xbmc/.xbmc/addons/plugin.video.myvideo_de/addon.py", line 193, in watch_video
video_url = scraper.get_video(video_id)
File "/home/xbmc/.xbmc/addons/plugin.video.myvideo_de/resources/lib/scraper.py", line 144, in get_video
sec = re.search(r_adv, html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
10:23:07 T:7377792 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.myvideo_de/video/8841658/]

**Comment by dersphere** [comment]
fixed with https://github.com/dersphere/plugin.video.myvideo_de/commit/911684bf8f7d2d9dacd3b8267f0341020d45bd87

Update will be available in a few days
