### ISSUE TITLE
addon.py error

### ISSUE THREAD

**Issue by philklei** [dersphere/plugin.video.myvideo_de#6]
hey,

after I installed 0.2.0 on eden i always go an error when i start to playback a video!

lg phil

**Comment by philklei** [comment]
Perhaps this helps you:

```
11:18:25 T:101011456  NOTICE: --- showSeries ok
11:18:25 T:83320832  NOTICE: CDVDPlayer::CloseFile()
11:18:25 T:83320832 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:18:25 T:83320832  NOTICE: DVDPlayer: waiting for threads to exit
11:18:25 T:83320832  NOTICE: DVDPlayer: finished waiting
11:24:25 T:101011456  NOTICE: -->Python Interpreter Initialized<--
11:24:26 T:101011456  NOTICE: --- showContent ok
11:24:28 T:98390016  NOTICE: -->Python Interpreter Initialized<--
11:24:39 T:98390016  NOTICE: -->Python Interpreter Initialized<--
11:24:41 T:98390016  NOTICE: [xbmcswift2] Request for "/" matches rule for function "show_categories"
11:24:41 T:98390016 WARNING: [plugin.video.myvideo_de] String is missing: webstars
11:24:44 T:127590400  NOTICE: -->Python Interpreter Initialized<--
11:24:45 T:127590400  NOTICE: [xbmcswift2] Request for "/category/Serien/" matches rule for function "show_subcategories"
11:24:45 T:127590400  NOTICE: MyVideo.de scraper: get_sub_categories started with path: Serien
11:24:45 T:127590400  NOTICE: MyVideo.de scraper: __get_url opening url: http://www.myvideo.de/
11:24:46 T:127590400  NOTICE: MyVideo.de scraper: __get_url got 140642 bytes
11:24:52 T:127590400  NOTICE: MyVideo.de scraper: skipping entry with link: /Serien/Serien_Suche
11:24:52 T:127590400  NOTICE: MyVideo.de scraper: skipping entry with link: /Serien/WWE
11:24:52 T:127590400  NOTICE: MyVideo.de scraper: skipping entry with link: /channel/unforgettable
11:24:52 T:127590400  NOTICE: MyVideo.de scraper: get_sub_categories finished with 13 elements
11:25:09 T:98390016  NOTICE: -->Python Interpreter Initialized<--
11:25:10 T:98390016  NOTICE: [xbmcswift2] Request for "/Serien%2FSat_1/" matches rule for function "show_path"
11:25:10 T:98390016  NOTICE: MyVideo.de scraper: get_path started with path: Serien/Sat_1
11:25:10 T:98390016  NOTICE: MyVideo.de scraper: __get_url opening url: http://www.myvideo.de/Serien/Sat_1
11:25:10 T:98390016  NOTICE: MyVideo.de scraper: __get_url got 198149 bytes
11:25:18 T:98390016  NOTICE: MyVideo.de scraper: Using Parser: __parse_shows
11:25:27 T:98390016  NOTICE: MyVideo.de scraper: __parse_shows finished with 89 elements
11:26:13 T:98390016  NOTICE: -->Python Interpreter Initialized<--
11:26:14 T:98390016  NOTICE: [xbmcswift2] Request for "/%2Fchannel%2Fnavy-cis/" matches rule for function "show_path"
11:26:14 T:98390016  NOTICE: MyVideo.de scraper: get_path started with path: /channel/navy-cis
11:26:14 T:98390016  NOTICE: MyVideo.de scraper: __get_url opening url: http://www.myvideo.de//channel/navy-cis
11:26:15 T:98390016  NOTICE: MyVideo.de scraper: __get_url got 73834 bytes
11:26:19 T:98390016  NOTICE: MyVideo.de scraper: Using Parser: __parse_channels
11:26:22 T:98390016  NOTICE: MyVideo.de scraper: __parse_channels assuming video channel
11:26:22 T:98390016  NOTICE: MyVideo.de scraper: __parse_channels finished with 2 elements
11:26:22 T:98390016   ERROR: Error Type: <type 'exceptions.TypeError'>
11:26:22 T:98390016   ERROR: Error Contents: argument 1 must be unicode or str
11:26:22 T:98390016   ERROR: Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/XBMC/addons/plugin.video.myvideo_de-master/addon.py", line 252, in <module>
                                                plugin.run()
                                              File "/var/mobile/Library/Preferences/XBMC/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 319, in run
                                                items = self._dispatch(self.request.path)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 295, in _dispatch
                                                listitems = view_func(**items)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/plugin.video.myvideo_de-master/addon.py", line 93, in show_path
                                                return __add_items(items)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/plugin.video.myvideo_de-master/addon.py", line 161, in __add_items
                                                return plugin.finish(items, **finish_kwargs)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 352, in finish
                                                self.add_items(items)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 267, in add_items
                                                item = xbmcswift2.ListItem.from_dict(**item)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/script.module.xbmcswift2/lib/xbmcswift2/listitem.py", line 208, in from_dict
                                                listitem.add_context_menu_items(context_menu)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/script.module.xbmcswift2/lib/xbmcswift2/listitem.py", line 59, in add_context_menu_items
                                                for label, action in items:
                                            TypeError: argument 1 must be unicode or str
11:26:22 T:83320832   ERROR: GetDirectory - Error getting plugin://plugin.video.myvideo_de/%2Fchannel%2Fnavy-cis/
11:26:22 T:83320832   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.myvideo_de/%2Fchannel%2Fnavy-cis/) failed
```

**Comment by dersphere** [comment]
I can't reproduce that issue. Can you send me a full xbmc debug log?

**Comment by philklei** [comment]
hey tristan,

i pasted the log to http://pastebin.com/kDjvSVCm

thx

**Comment by philklei** [comment]
does that informations helps you?

**Comment by dersphere** [comment]
No, I still can't reproduce. Can you try on Frodo?

**Comment by firsttris** [comment]
Hello,

more recently im always getting addon.py error.

Running Openelec 3.0.2 XBMC 12.2 (newest version)

I have 2 routers (Internet Endpoints):

the first router => conventional DSL myVideo addon works flawless...

the second router is connected via 4G Network... => myVideo addon shows addon.py error.

But i have no problem running any streaming addon with my second router, everything works flawless except myVideo.

My Log:
https://dl.dropboxusercontent.com/u/13344648/myVideo.txt

(PS: for some time ago the addon was working with both routers.)

**Comment by dersphere** [comment]
Please open a new issue if you still have any problems.
